version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: be.Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: fe.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
