version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: be.Dockerfile
    ports:
      - "8443:5000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: fe.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    volumes:
      - .:/app
