export const datas = [
    {
        id: '1',
        Timestamp: new Date(),
        Interface: 'Users',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'ADD USER',
        Message: '',
    },
    {
        id: '2',
        Timestamp: new Date(),
        Interface: 'Endpoint',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'ADD ENDPOINT',
        Message: '',
    },
    {
        id: '3',
        Timestamp: new Date(),
        Interface: 'Endpoint',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'EDIT ENDPOINT',
        Message: '',
    },
    {
        id: '4',
        Timestamp: new Date(),
        Interface: 'Publish',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'PUBLISH DATASET',
        Message: '',
    },
    {
        id: '5',
        Timestamp: new Date(),
        Interface: 'Publish',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'PUBLISH DATASET',
        Message: '',
    },
    {
        id: '6',
        Timestamp: new Date(),
        Interface: 'Catalog',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'EDIT METADATA',
        Message: '',
    },
    {
        id: '7',
        Timestamp: new Date(),
        Interface: 'Catalog',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'EDIT METADATA',
        Message: '',
    },
    {
        id: '8',
        Timestamp: new Date(),
        Interface: 'Catalog',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'EDIT METADATA',
        Message: '',
    },
    {
        id: '9',
        Timestamp: new Date(),
        Interface: 'Catalog',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'EDIT METADATA',
        Message: '',
    },
    {
        id: '10',
        Timestamp: new Date(),
        Interface: 'Approval',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'APPROVE',
        Message: '',
    },
    {
        id: '11',
        Timestamp: new Date(),
        Interface: 'Approval',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'APPROVE',
        Message: '',
    },
    {
        id: '12',
        Timestamp: new Date(),
        Interface: 'Approval',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'APPROVE',
        Message: '',
    },
    {
        id: '13',
        Timestamp: new Date(),
        Interface: 'Request',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'REQUEST DATASET',
        Message: '',
    },
    {
        id: '14',
        Timestamp: new Date(),
        Interface: 'Request',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'REQUEST DATASET',
        Message: '',
    },
    {
        id: '15',
        Timestamp: new Date(),
        Interface: 'Users',
        UserName: 'svc_adm_1',
        UserGroup: 'ADM_GRP',
        Role: 'Administrator',
        Activity: 'ADD User',
        Message: '',
    }   
];
